import path from 'node:path';

import type { ResolvedArchicatModule } from '@internal/model';
import { normalizePath, toPosixRelativeImport } from '@internal/path';
import { hasDefaultExport, listTypeScriptFiles } from '@internal/scanner';

import { writeTextFile } from '@internal/generator/file-writer';

// MARK: - Public

export function generateModuleMirrors(modules: readonly ResolvedArchicatModule[]): void {
  for (const module of modules) {
    generateApiMirror(module);
    generateImplMirror(module);
  }
}

// MARK: - Private

function generateApiMirror(module: ResolvedArchicatModule): void {
  if (!module.apiRootPath) {
    writeTextFile(path.join(module.mirrorApiRootPath, 'index.ts'), `${makeGeneratedHeader('empty api')}export {};\n`);
    return;
  }

  const apiFiles = listTypeScriptFiles(module.apiRootPath);
  const mirroredRelativePaths = new Set<string>();

  for (const sourceFilePath of apiFiles) {
    const relativePath = normalizePath(path.relative(module.apiRootPath, sourceFilePath));
    mirroredRelativePaths.add(relativePath);
    writeMirrorFile(path.join(module.mirrorApiRootPath, relativePath), sourceFilePath);
  }

  if (!mirroredRelativePaths.has('index.ts')) {
    writeTextFile(path.join(module.mirrorApiRootPath, 'index.ts'), `${makeGeneratedHeader('empty api index')}export {};\n`);
  }
}

function generateImplMirror(module: ResolvedArchicatModule): void {
  const implIndexPath = module.implRootPath ? findIndexFile(module.implRootPath) : undefined;

  if (!implIndexPath) {
    const content = `${makeGeneratedHeader('empty impl')}
export const ArchicatModuleImplementation = {
  id: '${module.id}',
  assemblies: [],
  schemas: [],
  routes: [],
} as const;

export default ArchicatModuleImplementation;
`;

    writeTextFile(path.join(module.mirrorImplRootPath, 'index.ts'), content);
    return;
  }

  writeMirrorFile(path.join(module.mirrorImplRootPath, 'index.ts'), implIndexPath);
}

function writeMirrorFile(targetFilePath: string, sourceFilePath: string): void {
  const sourceImport = toPosixRelativeImport(targetFilePath, sourceFilePath);
  const defaultExport = hasDefaultExport(sourceFilePath) ? `export { default } from '${sourceImport}';\n` : '';
  const content = `${makeGeneratedHeader('mirror')}
export * from '${sourceImport}';
${defaultExport}`;

  writeTextFile(targetFilePath, content);
}

function findIndexFile(rootPath: string): string | undefined {
  const candidates = ['index.ts', 'index.mts', 'index.cts', 'index.tsx'];

  for (const candidate of candidates) {
    const candidatePath = path.join(rootPath, candidate);

    if (listTypeScriptFiles(candidatePath).length > 0) {
      return candidatePath;
    }
  }

  return undefined;
}

function makeGeneratedHeader(reason: string): string {
  return `// Generated by ArchiCat (${reason}). Do not edit.\n`;
}
