import path from 'node:path';

import type { ResolvedArchicatProject } from '@internal/model';

import { writeTextFile } from '@internal/generator/file-writer';

// MARK: - Public

export function generateComposition(project: ResolvedArchicatProject): void {
  generateModules(project);
  generateCompositionEntry(project);
}

// MARK: - Private

function generateModules(project: ResolvedArchicatProject): void {
  const imports = project.modules
    .map((module) => `import * as ${makeImplementationIdentifier(module.id)} from '../modules/${module.id}/impl/index.js';`)
    .join('\n');

  const entries = project.modules
    .map((module) => `  { id: '${module.id}', implementation: ${makeImplementationIdentifier(module.id)} },`)
    .join('\n');

  const content = `// Generated by ArchiCat. Do not edit.
${imports}

export const ArchicatModules = [
${entries}
] as const;
`;

  writeTextFile(path.join(project.outDir, 'generated', 'modules.ts'), content);
}

function generateCompositionEntry(project: ResolvedArchicatProject): void {
  const content = `// Generated by ArchiCat. Do not edit.
import { ArchicatModules } from './modules.js';

export { ArchicatModules };

export function getArchicatModules() {
  return ArchicatModules;
}
`;

  writeTextFile(path.join(project.outDir, 'generated', 'composition.ts'), content);
}

function makeImplementationIdentifier(moduleId: string): string {
  return `${moduleId.replace(/-([a-z0-9])/gu, (_, char: string) => char.toUpperCase())}Implementation`;
}
