/**
 * @description Definition discovery roots for one Archicat definition kind.
 */
export interface ArchicatDefinitionRootConfig {
  /**
   * @description Directories or files where Archicat searches for matching definition marker files.
   */
  readonly include?: readonly string[];
}

/**
 * @description TypeScript alias prefixes reserved by Archicat.
 */
export interface ArchicatPrefixConfig {
  /**
   * @description Prefix for module public API aliases.
   * @default '@module'
   */
  readonly module?: string;

  /**
   * @description Prefix for library public API aliases.
   * @default '@library'
   */
  readonly library?: string;
}

/**
 * @description User TypeScript aliases generated into `.archicat/tsconfig.json`.
 * @default {}
 */
export type ArchicatAliasConfig = Readonly<Record<string, string>>;

/**
 * @description User-facing Archicat root config input.
 */
export interface ArchicatConfigInput {
  /**
   * @description Project root directory.
   * @default '.'
   */
  readonly root?: string;

  /**
   * @description Directory for generated mirror files, generated types, and reports.
   * @default '.archicat'
   */
  readonly outDir?: string;

  /**
   * @description User tsconfig file to merge into the generated Archicat tsconfig.
   * @default Auto-detects tsconfig.base.json, then tsconfig.json.
   */
  readonly tsconfig?: string;

  /**
   * @description User TypeScript aliases generated by Archicat.
   * @default {}
   */
  readonly alias?: ArchicatAliasConfig;

  /**
   * @description Reserved TypeScript import prefixes generated by Archicat.
   * @default { module: '@module', library: '@library' }
   */
  readonly prefixes?: ArchicatPrefixConfig;

  /**
   * @description Module definition discovery config.
   * @default { include: ['./src/modules'] }
   */
  readonly modules?: ArchicatDefinitionRootConfig;

  /**
   * @description Library definition discovery config.
   * @default { include: [] }
   */
  readonly libraries?: ArchicatDefinitionRootConfig;

  /**
   * @description App composition definition discovery config.
   * @default { include: [] }
   */
  readonly apps?: ArchicatDefinitionRootConfig;
}

/**
 * @description Normalized immutable Archicat config contract.
 */
export type ArchicatConfig = Readonly<{
  readonly root?: string;
  readonly outDir?: string;
  readonly tsconfig?: string;
  readonly alias?: ArchicatAliasConfig;
  readonly prefixes?: Readonly<{
    readonly module?: string;
    readonly library?: string;
  }>;
  readonly modules?: Readonly<{
    readonly include?: readonly string[];
  }>;
  readonly libraries?: Readonly<{
    readonly include?: readonly string[];
  }>;
  readonly apps?: Readonly<{
    readonly include?: readonly string[];
  }>;
}>;
