/**
 * @description Definition discovery roots for one Archicat definition kind.
 */
export interface ArchicatDefinitionRootConfig {
  /**
   * @description Directories or files where Archicat searches for matching definition marker files.
   */
  readonly include?: readonly string[];
}

/**
 * @description TypeScript config fragment merged into generated `.archicat/tsconfig.json`.
 */
export interface ArchicatTypeScriptTsConfigInput {
  /**
   * @description Base TypeScript config extended by generated `.archicat/tsconfig.json`.
   */
  readonly extends?: string;

  /**
   * @description Project source files merged into generated `.archicat/tsconfig.json` include.
   * Archicat rewrites relative paths to the generated config directory and appends generated type declarations automatically.
   */
  readonly include?: readonly string[];

  /**
   * @description Project paths merged into generated `.archicat/tsconfig.json` exclude.
   * Archicat rewrites relative paths to the generated config directory.
   */
  readonly exclude?: readonly string[];

  /**
   * @description Project files merged into generated `.archicat/tsconfig.json` files.
   * Archicat rewrites relative paths to the generated config directory.
   */
  readonly files?: readonly string[];

  /**
   * @description Unsupported. Put compiler options in the base or app tsconfig. Archicat owns generated `compilerOptions.paths` and does not support `baseUrl`.
   */
  readonly compilerOptions?: {
    readonly paths?: never;
    readonly baseUrl?: never;
  };
}

/**
 * @description TypeScript integration options used to generate `.archicat/tsconfig.json`.
 */
export interface ArchicatTypeScriptConfigInput {
  /**
   * @description Partial TypeScript config merged into generated `.archicat/tsconfig.json`.
   * Archicat rewrites relative paths from the project root to `.archicat`, appends generated type declarations to `include`, and injects generated aliases into `compilerOptions.paths`.
   * `compilerOptions` is not supported here. Put compiler policy in the base tsconfig and app build overrides in the app tsconfig.
   * @default {}
   */
  readonly tsConfig?: ArchicatTypeScriptTsConfigInput;
}

/**
 * @description TypeScript alias prefixes reserved by Archicat.
 */
export interface ArchicatPrefixConfig {
  /**
   * @description Prefix for module public API aliases.
   * @default '@module'
   */
  readonly module?: string;

  /**
   * @description Prefix for library public API aliases.
   * @default '@library'
   */
  readonly library?: string;
}

/**
 * @description User import aliases generated into `.archicat/tsconfig.json` together with Archicat module and library aliases.
 * Aliases are resolved relative to the Archicat project root. Do not define TypeScript `compilerOptions.paths` manually for an Archicat project.
 * @default {}
 */
export type ArchicatAliasConfig = Readonly<Record<string, string>>;

/**
 * @description User-facing Archicat root config input.
 */
export interface ArchicatConfigInput {
  /**
   * @description Project root directory.
   * @default '.'
   */
  readonly root?: string;

  /**
   * @description Directory for generated mirror files, generated types, and reports.
   * @default '.archicat'
   */
  readonly outDir?: string;

  /**
   * @description TypeScript integration options used to generate `.archicat/tsconfig.json`.
   * @default {}
   */
  readonly typescript?: ArchicatTypeScriptConfigInput;

  /**
   * @description User TypeScript aliases generated by Archicat.
   * @default {}
   */
  readonly alias?: ArchicatAliasConfig;

  /**
   * @description Reserved TypeScript import prefixes generated by Archicat.
   * @default { module: '@module', library: '@library' }
   */
  readonly prefixes?: ArchicatPrefixConfig;

  /**
   * @description Module definition discovery config.
   * @default { include: ['./src/modules'] }
   */
  readonly modules?: ArchicatDefinitionRootConfig;

  /**
   * @description Library definition discovery config.
   * @default { include: [] }
   */
  readonly libraries?: ArchicatDefinitionRootConfig;

  /**
   * @description App composition definition discovery config.
   * @default { include: [] }
   */
  readonly apps?: ArchicatDefinitionRootConfig;
}

/**
 * @description Normalized immutable Archicat config contract.
 */
export type ArchicatConfig = Readonly<{
  readonly root?: string;
  readonly outDir?: string;
  readonly typescript?: Readonly<{
    readonly tsConfig?: Readonly<{
      readonly extends?: string;
      readonly include?: readonly string[];
      readonly exclude?: readonly string[];
      readonly files?: readonly string[];
      readonly compilerOptions?: Readonly<{
        readonly paths?: never;
        readonly baseUrl?: never;
      }>;
    }>;
  }>;
  readonly alias?: ArchicatAliasConfig;
  readonly prefixes?: Readonly<{
    readonly module?: string;
    readonly library?: string;
  }>;
  readonly modules?: Readonly<{
    readonly include?: readonly string[];
  }>;
  readonly libraries?: Readonly<{
    readonly include?: readonly string[];
  }>;
  readonly apps?: Readonly<{
    readonly include?: readonly string[];
  }>;
}>;
